'''
        self.lbTitle11 = QLabel(self)
        self.lbTitle11.setObjectName(u"lbTitle11")
        sizePolicy_PF.setHeightForWidth(self.lbTitle11.sizePolicy().hasHeightForWidth())
        self.lbTitle11.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle11, 0, 1, 1, 1)

        self.lbTitle12 = QLabel(self)
        self.lbTitle12.setObjectName(u"lbTitle12")
        sizePolicy_PF.setHeightForWidth(self.lbTitle12.sizePolicy().hasHeightForWidth())
        self.lbTitle12.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle12, 0, 2, 1, 1)

        self.lbTitle13 = QLabel(self)
        self.lbTitle13.setObjectName(u"lbTitle13")
        sizePolicy_PF.setHeightForWidth(self.lbTitle13.sizePolicy().hasHeightForWidth())
        self.lbTitle13.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle13, 0, 3, 1, 1)

        self.lbTitle14 = QLabel(self)
        self.lbTitle14.setObjectName(u"lbTitle14")
        sizePolicy_PF.setHeightForWidth(self.lbTitle14.sizePolicy().hasHeightForWidth())
        self.lbTitle14.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle14, 0, 4, 1, 1)
        
        self.lbTitle15 = QLabel(self)
        self.lbTitle15.setObjectName(u"lbTitle15")
        sizePolicy_PF.setHeightForWidth(self.lbTitle15.sizePolicy().hasHeightForWidth())
        self.lbTitle15.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle15, 0, 5, 1, 1)

        self.lbTitle21 = QLabel(self)
        self.lbTitle21.setObjectName(u"lbTitle21")
        sizePolicy_PF.setHeightForWidth(self.lbTitle21.sizePolicy().hasHeightForWidth())
        self.lbTitle21.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle21, 1, 1, 1, 1)

        self.lbTitle22 = QLabel(self)
        self.lbTitle22.setObjectName(u"lbTitle22")
        sizePolicy_PF.setHeightForWidth(self.lbTitle22.sizePolicy().hasHeightForWidth())
        self.lbTitle22.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle22, 1, 2, 1, 1)

        self.lbTitle23 = QLabel(self)
        self.lbTitle23.setObjectName(u"lbTitle23")
        sizePolicy_PF.setHeightForWidth(self.lbTitle23.sizePolicy().hasHeightForWidth())
        self.lbTitle23.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle23, 1, 3, 1, 1)

        self.lbTitle24 = QLabel(self)
        self.lbTitle24.setObjectName(u"lbTitle24")
        sizePolicy_PF.setHeightForWidth(self.lbTitle24.sizePolicy().hasHeightForWidth())
        self.lbTitle24.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle24, 1, 4, 1, 1)

        self.lbTitle25 = QLabel(self)
        self.lbTitle25.setObjectName(u"lbTitle25")
        sizePolicy_PF.setHeightForWidth(self.lbTitle25.sizePolicy().hasHeightForWidth())
        self.lbTitle25.setSizePolicy(sizePolicy_PF)
        self.glMain.addWidget(self.lbTitle25, 1, 5, 1, 1)

        self.lnAns11 = QLineEdit(self)
        self.lnAns11.setObjectName(u"lnAns11")
        sizePolicy_FF.setHeightForWidth(self.lnAns11.sizePolicy().hasHeightForWidth())
        self.lnAns11.setSizePolicy(sizePolicy_FF)
        self.lnAns11.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns11, 2, 1, 1, 1)

        self.lnAns12 = QLineEdit(self)
        self.lnAns12.setObjectName(u"lnAns12")
        sizePolicy_FF.setHeightForWidth(self.lnAns12.sizePolicy().hasHeightForWidth())
        self.lnAns12.setSizePolicy(sizePolicy_FF)
        self.lnAns12.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns12, 2, 2, 1, 1)

        self.lnAns13 = QLineEdit(self)
        self.lnAns13.setObjectName(u"lnAns13")
        sizePolicy_FF.setHeightForWidth(self.lnAns13.sizePolicy().hasHeightForWidth())
        self.lnAns13.setSizePolicy(sizePolicy_FF)
        self.lnAns13.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns13, 2, 3, 1, 1)

        self.lnAns14 = QLineEdit(self)
        self.lnAns14.setObjectName(u"lnAns14")
        sizePolicy_FF.setHeightForWidth(self.lnAns14.sizePolicy().hasHeightForWidth())
        self.lnAns14.setSizePolicy(sizePolicy_FF)
        self.lnAns14.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns14, 2, 4, 1, 1)

        self.lnAns15 = QLineEdit(self)
        self.lnAns15.setObjectName(u"lnAns15")
        sizePolicy_FF.setHeightForWidth(self.lnAns15.sizePolicy().hasHeightForWidth())
        self.lnAns15.setSizePolicy(sizePolicy_FF)
        self.lnAns15.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns15, 2, 5, 1, 1)

        self.lnAns21 = QLineEdit(self)
        self.lnAns21.setObjectName(u"lnAns21")
        sizePolicy_FF.setHeightForWidth(self.lnAns21.sizePolicy().hasHeightForWidth())
        self.lnAns21.setSizePolicy(sizePolicy_FF)
        self.lnAns21.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns21, 3, 1, 1, 1)

        self.lnAns22 = QLineEdit(self)
        self.lnAns22.setObjectName(u"lnAns22")
        sizePolicy_FF.setHeightForWidth(self.lnAns22.sizePolicy().hasHeightForWidth())
        self.lnAns22.setSizePolicy(sizePolicy_FF)
        self.lnAns22.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns22, 3, 2, 1, 1)

        self.lnAns23 = QLineEdit(self)
        self.lnAns23.setObjectName(u"lnAns23")
        sizePolicy_FF.setHeightForWidth(self.lnAns23.sizePolicy().hasHeightForWidth())
        self.lnAns23.setSizePolicy(sizePolicy_FF)
        self.lnAns23.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns23, 3, 3, 1, 1)

        self.lnAns24 = QLineEdit(self)
        self.lnAns24.setObjectName(u"lnAns24")
        sizePolicy_FF.setHeightForWidth(self.lnAns24.sizePolicy().hasHeightForWidth())
        self.lnAns24.setSizePolicy(sizePolicy_FF)
        self.lnAns24.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns24, 3, 4, 1, 1)

        self.lnAns25 = QLineEdit(self)
        self.lnAns25.setObjectName(u"lnAns25")
        sizePolicy_FF.setHeightForWidth(self.lnAns25.sizePolicy().hasHeightForWidth())
        self.lnAns25.setSizePolicy(sizePolicy_FF)
        self.lnAns25.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnAns25, 3, 5, 1, 1)

        self.lnCor11 = QLineEdit(self)
        self.lnCor11.setObjectName(u"lnCor11")
        sizePolicy_FF.setHeightForWidth(self.lnCor11.sizePolicy().hasHeightForWidth())
        self.lnCor11.setSizePolicy(sizePolicy_FF)
        self.lnCor11.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor11, 4, 1, 1, 1)

        self.lnCor12 = QLineEdit(self)
        self.lnCor12.setObjectName(u"lnCor12")
        sizePolicy_FF.setHeightForWidth(self.lnCor12.sizePolicy().hasHeightForWidth())
        self.lnCor12.setSizePolicy(sizePolicy_FF)
        self.lnCor12.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor12, 4, 2, 1, 1)

        self.lnCor13 = QLineEdit(self)
        self.lnCor13.setObjectName(u"lnCor13")
        sizePolicy_FF.setHeightForWidth(self.lnCor13.sizePolicy().hasHeightForWidth())
        self.lnCor13.setSizePolicy(sizePolicy_FF)
        self.lnCor13.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor13, 4, 3, 1, 1)

        self.lnCor14 = QLineEdit(self)
        self.lnCor14.setObjectName(u"lnCor14")
        sizePolicy_FF.setHeightForWidth(self.lnCor14.sizePolicy().hasHeightForWidth())
        self.lnCor14.setSizePolicy(sizePolicy_FF)
        self.lnCor14.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor14, 4, 4, 1, 1)

        self.lnCor15 = QLineEdit(self)
        self.lnCor15.setObjectName(u"lnCor15")
        sizePolicy_FF.setHeightForWidth(self.lnCor15.sizePolicy().hasHeightForWidth())
        self.lnCor15.setSizePolicy(sizePolicy_FF)
        self.lnCor15.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor15, 4, 5, 1, 1)

        self.lnCor21 = QLineEdit(self)
        self.lnCor21.setObjectName(u"lnCor21")
        sizePolicy_FF.setHeightForWidth(self.lnCor21.sizePolicy().hasHeightForWidth())
        self.lnCor21.setSizePolicy(sizePolicy_FF)
        self.lnCor21.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor21, 5, 1, 1, 1)

        self.lnCor22 = QLineEdit(self)
        self.lnCor22.setObjectName(u"lnCor22")
        sizePolicy_FF.setHeightForWidth(self.lnCor22.sizePolicy().hasHeightForWidth())
        self.lnCor22.setSizePolicy(sizePolicy_FF)
        self.lnCor22.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor22, 5, 2, 1, 1)

        self.lnCor23 = QLineEdit(self)
        self.lnCor23.setObjectName(u"lnCor23")
        sizePolicy_FF.setHeightForWidth(self.lnCor23.sizePolicy().hasHeightForWidth())
        self.lnCor23.setSizePolicy(sizePolicy_FF)
        self.lnCor23.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor23, 5, 3, 1, 1)

        self.lnCor24 = QLineEdit(self)
        self.lnCor24.setObjectName(u"lnCor24")
        sizePolicy_FF.setHeightForWidth(self.lnCor24.sizePolicy().hasHeightForWidth())
        self.lnCor24.setSizePolicy(sizePolicy_FF)
        self.lnCor24.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor24, 5, 4, 1, 1)

        self.lnCor25 = QLineEdit(self)
        self.lnCor25.setObjectName(u"lnCor25")
        sizePolicy_FF.setHeightForWidth(self.lnCor25.sizePolicy().hasHeightForWidth())
        self.lnCor25.setSizePolicy(sizePolicy_FF)
        self.lnCor25.setMaximumSize(QSize(100, 16777215))
        self.glMain.addWidget(self.lnCor25, 5, 5, 1, 1)
        '''